### ISSUE TITLE
Re-Test all recipes

### ISSUE THREAD

**Issue by dugite-code** [feediron/ttrss_plugin-feediron#100]
There are recipes that are quite old and should be re-tested against current websites the updated/deleted were appropriate.

Note: Deletes are where nothing works, updates are where there are only a few minor glitches

- [x] abgeordnetenwatch_de **- Del**
- [x] aljazeera **-Del**
- [x] androidpolice_com
- [x] ap **- Unable to find test feed - Del**
- [x] arstechnica
- [x] backchannel_com **-Del No longer exists part of Wired.com**
- [x] bangkokpost **- Del**
- [x] bbc.com **- New**
- [x] bgr **- Del**
- [x] breitbart.com **- New**
- [x] buenosairesherald **- Del**
- [x] chefkoch_de **- Del**
- [x] cnet _**- Needs Update**_
- [x] csmonitor **- Del**
- [x] dailymail.co.uk **- New**
- [ ] dailytech
- [x] der-farang_com
- [ ] der-postillon_com
- [x] dilbert_com
- [ ] discovermagazine
- [ ] dorkly.com
- [ ] epitition_bundestag_de
- [ ] feedblitz
- [ ] foxnews.com
- [x] fredericksburg.com **- New**
- [ ] geek
- [x] github **- Del**
- [x] github_releases _**- Needs update**_
- [ ] golem_de
- [ ] heise_de
- [ ] heise_de_developer
- [ ] heise_de_newsticker
- [ ] heise_de_technology_review
- [ ] heise_de_telepolis
- [ ] heise_de_tr
- [x] hiveworks **- New**
- [ ] japantimes
- [ ] japantoday
- [ ] jsonline
- [ ] koreaherald
- [ ] lesjoiesducode.fr-image
- [ ] linux **- Del**
- [ ] linuxinsider _**- Needs update**_
- [ ] managewp.org
- [ ] massivelyop_com
- [ ] merkur_de
- [ ] moderntokyotimes
- [ ] muckrock
- [ ] nba
- [x] nbc12.com **- New**
- [ ] networkworld
- [ ] npr
- [ ] opensource.com
- [ ] postillon_de
- [ ] recode
- [ ] sankakucomplex
- [ ] scienexx_de
- [ ] securityfocus
- [ ] smashingmagazine.com
- [ ] soundandvision
- [ ] spiegel_de
- [ ] stereophile.com
- [ ] sz_de
- [ ] tagesspiegel
- [ ] theatlantic
- [x] theguardian.com **- New**
- [x] thehill.com **- New**
- [ ] thehindu
- [ ] themoscowtimes
- [ ] thenewslens
- [ ] theoatmeal_com
- [ ] thestandard
- [ ] time.com
- [ ] titanic-magazin_de
- [ ] toonpool_com
- [ ] upi
- [ ] wired
- [ ] wonderhowto.com
- [x] xkcd_com
- [ ] yahoo.com
- [x] zdnet
- [ ] zeit_de

**Comment by JReming85** [comment]
I'll take a stab at working on some of them

**Comment by JReming85** [comment]
@dugite-code looks like AP is dead, http://www.hosted.ap.org routes to apnews.com.

I'll have to turn off my other AP plugin to test it, but ill write a new config in a bit
