### ISSUE TITLE
Unable to run/test configuration

### ISSUE THREAD

**Issue by tushartyagi** [feediron/ttrss_plugin-feediron#115]
# Expected Behavior

Testing the feed should populate the result in the "result" tab.

# Current Behavior

I tried running the xkcd example given in the readme file, but it doesn't seem to work. I get no output in the "testing" tab, and no helpful message in the System logs.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Installed & enabled feediron. Getting the "Feediron" tab in user interface. 
2. Selected "xkcd_com" from predefined rules & clicked on Add: Nothing happens.
3. Gave the following configuration to add a rule in the configuration text area:

```json
{
    "xkcd.com": {
        "type": "xpath",
        "xpath": [ 
             "div[contains(@id,'comic')]", 
             "div[contains(@id, 'comic')]\/img\/@title"
        ],
        "join_element": "<p \/>"
    },
    "debug": "true"
}
````
4. Clicked on Add, nothing happens. Expected: A page load or some message. Actual: Nothing. No error in system log as well.

5. Tried testing the example config in the testing section. using the following config:

```json
{
    "type": "xpath",
    "xpath": [ 
         "div[contains(@id,'comic')]", 
         "div[contains(@id, 'comic')]\/img\/@title"
    ],
    "join_element": "<p \/>"
}
```
6. No progress on the screen. Expected: the xkcd comic should load. Actual: Stack trace (?) in system logs.

# Failure Information (for bugs)

![image](https://user-images.githubusercontent.com/1630265/50580582-33d46c80-0e76-11e9-8348-ef1899d56db0.png)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Debian 9
* TTRSS version/git version: Tiny Tiny RSS v18.12 (734af33)
* PHP version: PHP 7.0.33-0
* Feediron Configuration: NA
* Feediron branch/commit: master/407168c628880b5ced572cc549db6d50e866d3c8

**Comment by dugite-code** [comment]
Yes the add function dosn't give any notification feedback. This is defiantly a bad fist user experience issue.

1. select feed example, press add
2. Press save (Don't think it's necessary but always a good idea)

**Next time** TT-RSS updates the XKCD feed it will use that rule to process.

As for the testing area The log looks like it ran successfully so it's hard to say.

Do feed load normally?

If you right click and in Inspect element is there anything in the Result tab of the Testing Tab?

Example:
```html
<div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="selected:true" id="test_result" class="dijitContentPane dijitTabPane dijitTabContainerTop-child dijitTabContainerTop-dijitContentPane" widgetid="test_result" style="left: 0px; top: 0px; width: 1846px; height: 500px;">
    <img src="//imgs.xkcd.com/comics/goto.png" title="Neal Stephenson thinks it's cute to name his labels 'dengo'" alt="goto">Neal Stephenson thinks it's cute to name his labels 'dengo'
</div>
```

I'm running  v18.8 (642677d) at the moment I'll update sometime the week after next if you keep having issues.

**Comment by tushartyagi** [comment]
I inspected the results pane, and it shows the following html:

```html
<div data-dojo-type="dijit/layout/ContentPane"
data-dojo-props="selected:true" id="test_result"
class="dijitContentPanedijitTabPane dijitTabContainerTop-child dijitTabContainerTop-dijitContentPane" widgetid="test_result"
style="left: 0px; top: 0px; width: 1329.33px; height: 108.333px;"></div>
```

So the img element is missing from results.

One thing that I'm trying to understand is the concept of "predefined
rules". If I add these, are these added some backend configuration and
used behind the scenes?

If I select any rule, and click on add, and let's say the rule is
added. Will it merge with the Configuration that I give in the text
area?

I'm asking this because I used an existing rule, and added its feed in
order to test, but it's not working. I'm still getting just a one-line
blurb in the feed and have to go to the website to read the actual article.

dugite-code writes:

> Yes the add function dosn't give any notification feedback. This is defiantly a bad fist user experience issue.
>
> 1. select feed example, press add
> 2. Press save (Don't think it's necessary but always a good idea)
>
> **Next time** TT-RSS updates the XKCD feed it will use that rule to process.
>
> As for the testing area The log looks like it ran successfully so it's hard to say.
>
> Do feed load normally?
>
> If you right click and in Inspect element is there anything in the Result tab of the Testing Tab?
>
> Example:
> ```html
> <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="selected:true" id="test_result" class="dijitContentPane dijitTabPane dijitTabContainerTop-child dijitTabContainerTop-dijitContentPane" widgetid="test_result" style="left: 0px; top: 0px; width: 1846px; height: 500px;">
>     <img src="//imgs.xkcd.com/comics/goto.png" title="Neal Stephenson thinks it's cute to name his labels 'dengo'" alt="goto">Neal Stephenson thinks it's cute to name his labels 'dengo'
> </div>
> ```
>
> I'm running  v18.8 (642677d) at the moment I'll update sometime the week after next if you keep having issues.


-- 
With best regards,
Tushar Tyagi

**Comment by tushartyagi** [comment]
@dugite-code While I've not been able to test the code, the functionality is working if I write the configuration for individual websites. 
I just have to wait for the feed to load again the next time background job runs. 

Perhaps we can close the ticket?

**Comment by Narga** [comment]
I had the same problem.
Today, after updated TTRSS to newest version from git. I received a ton of messed content. When I retest feeds with feediron, the testing couldn't load the configuration and display nothing when press the test button
I change the correct DOM inspected and save the configuration (it's work but not display any notification about the save proccess), reload the feed with new content the I got messed again.
Here is the screenshot of system log.
![screenshot_2019-01-09 tiny tiny rss preferences](https://user-images.githubusercontent.com/212624/50874244-ecaa2680-13f5-11e9-8134-463fa2e5f798.png)

**Comment by tushartyagi** [comment]
This issue was posted by a plugin author recently:

https://discourse.tt-rss.org/t/scriptaliculous-controls-js-failing-to-load-after-recent-updates-breaking-plugins/1741

Fox says: 

"due to many recent changes in base tt-rss code, pretty much all plugins with javascript code will have to be updated"

I guess feediron also needs to be updated?! 

On 9 January 2019 8:34:22 AM IST, "Nguyễn Đình Quân" <notifications@github.com> wrote:
>I had the same problem.
>Today, after updated TTRSS to newest version from git. I received a ton
>of messed content. When I retest feeds with feediron, the testing
>couldn't load the configuration and display nothing when press the test
>button
>I change the correct DOM inspected and save the configuration (it's
>work but not display any notification about the save proccess), reload
>the feed with new content the I got messed again.
>Here is the screenshot of system log.
>![screenshot_2019-01-09 tiny tiny rss
>preferences](https://user-images.githubusercontent.com/212624/50874244-ecaa2680-13f5-11e9-8134-463fa2e5f798.png)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/feediron/ttrss_plugin-feediron/issues/115#issuecomment-452555255

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dugite-code** [comment]
Yes that could be the issue. I'm hoping I'll be able to look into it properly next week.

**Comment by dugite-code** [comment]
@tushartyagi @Narga could you please Test https://github.com/feediron/ttrss_plugin-feediron/commit/2e83ce08edad3ce0f8c82b1ea732419a6a2de891 ?

From my testing the change was relatively minor

**Comment by Narga** [comment]
Tested, it works like charm again :+1:

**Comment by dugite-code** [comment]
[Version 1.1.1](https://github.com/feediron/ttrss_plugin-feediron/releases/tag/v1.1.1)

**Comment by tushartyagi** [comment]
Splendid! This works like a charm.
Thanks @dugite-code! 

dugite-code writes:

> @tushartyagi @Narga could you please Test 2e83ce0 ?
>
> From my testing the change was relatively minor
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.


-- 
With best regards,
Tushar Tyagi
