### ISSUE TITLE
PHP fatal error on line 663

### ISSUE THREAD

**Issue by rom-1** [feediron/ttrss_plugin-feediron#128]
Using newest feediron and TinyTinyRSS build, I am getting a uncaught error message in the TTRSS Log when testing a new configuration rule.

For testing purposes, my configuration rule is quite simple: 
   "eurogamer": {
        "type": "xpath",
        "xpath": "article"
    },

My testing URL: https://www.eurogamer.net/articles/2019-03-06-devil-may-cry-5-review-an-unashamedly-old-school-retooling-of-an-action-classic

Error Log: plugins.local/feediron/init.php:663

```
Uncaught Error: Call to a member function cleanRepair() on boolean in /plugins.local/feediron/init.php:663 Stack trace: #0 /plugins.local/feediron/init.php(223): Feediron->processArticle('<header class="...', Array, 'https://www.eur...') #1 /plugins.local/feediron/init.php(1083): Feediron->getNewContent('https://www.eur...', Array) #2 /classes/pluginhandler.php(12): Feediron->test() #3 /backend.php(126): PluginHandler->catchall('test') #4 {main} thrown | admin | 18:34
------------
tidy_parse_string(): Could not set encoding 'ISO88591'
```

**Comment by dugite-code** [comment]
That's a bug, It shouldn't be calling tidy unless explicitly told to

**Comment by dugite-code** [comment]
Ok I've added some charset maps to validate and fix the output. I've also thrown a exception catch on that tidy.

**Comment by rom-1** [comment]
Works like a charm, thanks for the quick fix!
