### ISSUE TITLE
Problems with rule

### ISSUE THREAD

**Issue by Carsten3000** [feediron/ttrss_plugin-feediron#129]
Hello,

at this website 

https://www.heise.de/newsticker/meldung/Lohnangleichung-bei-Google-Maenner-staerker-unterbezahlt-4326808.html?wt_mc=rss.ho.beitrag.atom

i am having trouble blocking this part:

![image](https://user-images.githubusercontent.com/43674046/54448702-a1d9c180-474c-11e9-85b6-5c921c31c88a.png)

my code:
`{
    "type": "xpath",
    "xpath": [
        "article[contains(@class,'article-layout')]"
    ],
    "multipage": {
        "xpath": "a[@rel='nofollow' and @class='pagination-all-on-one-page__link']",
        "append": false
    },
    "cleanup": [
        "div[contains(@class,'article-header__publish-info')]",
        "div[contains(@class,'article-actions')]",
        "aside[contains(@class,'top-ad-container')]",
        "aside[contains(@class,'akwa-ad-container')]",
        "section[contains(@class,'article-sidebar')]"
    ]
}`

Why doesnt my ` "section[contains(@class,'article-sidebar')]"` not work?

I really appreciate any help you can provide.

**Comment by de-es** [comment]
It does look like it isn't cleaned up but in fact it is. There are two instances of the same content for responsive design reasons. Just add `"a-collapse"` to your cleanup.

**Comment by dugite-code** [comment]
as @de-es has pointed out it's caused by responsive design issues using a catch-all contains xpath looks to be your best bet `"*[contains(@class,'collapse-box')]"`

```json
{
    "type": "xpath",
    "xpath": [
        "article[contains(@class,'article-layout')]"
    ],
    "multipage": {
        "xpath": "a[@rel='nofollow' and @class='pagination-all-on-one-page__link']",
        "append": false
    },
    "cleanup": [
        "div[contains(@class,'article-header__publish-info')]",
        "div[contains(@class,'article-actions')]",
        "aside[contains(@class,'top-ad-container')]",
        "aside[contains(@class,'akwa-ad-container')]",
        "section[contains(@class,'article-sidebar')]",
        "*[contains(@class,'collapse-box')]",
        "footer"
    ]
}
```
