### ISSUE TITLE
Feature/Question: apply to all links within feed

### ISSUE THREAD

**Issue by a-bali** [feediron/ttrss_plugin-feediron#140]
There are several feeds that are just a collection of links to various websites. Therefore the links can't be matched with a pattern (can be any site really) and there is no `<author>` tag in the feed. Would it be possible to somehow apply feediron to download all links of a specified feed?

Example feed [here](https://news.ycombinator.com/rss)

**Comment by dugite-code** [comment]
Feed iron is really designed for site specific full-text fetching, you're looking for a more generic solution like the [mercury fulltext pugin](https://github.com/HenryQW/mercury_fulltext) or the af_readability plugin.

I don't think I would be open to adding such a feature at this time. It would be something I would add if/when I add a way to fall back to the feed content if a recipe fails to collect the content.
