### ISSUE TITLE
"spl_autoload_register" causes warnings in ttrss system log

### ISSUE THREAD

**Issue by iWantToKeepAnon** [feediron/ttrss_plugin-feediron#148]
# Prerequisites

- [ x ] I am running the latest version
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed

# Expected Behavior

Non error/warning integration into tt-rss, playing friendly with other plugins.

# Current Behavior

Feediron is placing a warning into tt-rss system log every time {myPlugin} (named redacted) uses "class_exists" due to (AFAICT) "spl_autoload_register".

## Steps to Reproduce

I have a personal plugin that I have not yet released, it exectues:
   `if (class_exists($className)) {…}`

and feediron enters a warning into the tt-rss system log:
```php
include(): Failed opening 'filters/{myClass}/init.php' for inclusion (include_path='/.../ttrss/...')
1. plugins.local/feediron/init.php(14): ttrss_error_handler(2, include(): Failed opening 'filters/{myClass}/init.php' for inclusion (include_path='...'), plugins.local/feediron/init.php, 14, Array)
2. plugins.local/feediron/init.php(14): include()
3. plugins.local/{myPlugin}/init.php(26): class_exists({myClass})
4. plugins.local/{myPlugin}/init.php(49): {myFunction)(…)
5. classes/rssutils.php(345): hook_fetch_feed(...)
6. classes/feeds.php(840): update_rss_feed(...)
```

You can see that execution jumps from {myPlugin} to feediron init.php(14).  Can the "spl_autoload_register" function be limited to code in feediron's scope?

# Failure Information (for bugs)

Not sure this is a full blown bug, but definitely a feature.  I am kind of surprised that the ttrss codebase doesn't trigger these warnings when it uses class_exists. I skipped autoloading code by changing my call to `class_exists($className, false)` and that fixes the warnings, but that shouldn't be necessary.  Right?

I am not a php expert, am I missing something obvious?

## Context

* Operating System: linux (centos) and windows (10)
* TTRSS version/git version: always on a fresh master pull
* PHP version: v7.1
* Feediron Configuration: N/A, the warning is triggered from another plugin regardless of feediron configs.

**Comment by dugite-code** [comment]
Unfortunately I've not been able to use namespaces in FeedIron, I believe that would be the ideal way to address the issue. It's not a major issue per-say, it's 

I've added some fixes in https://github.com/feediron/ttrss_plugin-feediron/commit/556634628562ad23c1347b36ff55511651caf514 that should address this issue

**Comment by iWantToKeepAnon** [comment]
Perfect, thanks for a quick turn around! : ))
