### ISSUE TITLE
Content behind privacy wall

### ISSUE THREAD

**Issue by feedspeed** [feediron/ttrss_plugin-feediron#155]
I tried multiple ways, but didn't manage so far; would this plugin actually be capable to scrape something behind a cookie wall with a button element to accept? 
A lot of Dutch websites are using a redirect to a privacy wall. Content is only scrapable after getting a link from the button element. E.g. www.volkskrant.nl, www.trouw.nl and www.vi.nl.

**Comment by dugite-code** [comment]
Unfortunately no. There is a chance just changing the user agent will fix your issue, You could look into the plugin [ttrss-tumblr-gdpr ](https://github.com/GregThib/ttrss-tumblr-gdpr), you'll have to add the domain's to the supported array: https://github.com/GregThib/ttrss-tumblr-gdpr/blob/master/init.php#L29
