### ISSUE TITLE
Unrecognized option:  fi_mod_

### ISSUE THREAD

**Issue by damionx7** [feediron/ttrss_plugin-feediron#160]
# Expected Behavior

Feediron should change the feed

# Current Behavior

It does nothing and in testing tab, gives the error : `Unrecognized option:  fi_mod_`

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.
1. install feediron
2. Enable in plugins
3. In testing tab, test the url `https://theprint.in/judiciary/supreme-court-restrains-banks-from-declaring-accounts-as-npas-until-further-notice/495066/`
4. Use this config
```
{
    "theprint.in": {
        "type": "xpath",
        "xpath": "div[contains(@class, 'id-article-body')]"
    }
}
```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Debian Buster 10
* TTRSS version/git version: 67f02e2aa7b246ef7ca2b2aa4c62e2826327d219
* PHP version: 7.3.19-1~deb10u1
* Feediron Configuration: 

```json
{
    "xkcd.com": {
        "type": "xpath",
        "xpath": [
            "div[contains(@id,'comic')]",
            "div[contains(@id,'comic')]\/\/img\/@title"
        ],
        "join_element": "<p>"
    },
    "\/releases\/tag\/": {
        "type": "xpath",
        "xpath": "div[contains(@class, 'release-body')]",
        "cleanup": [
            "h1"
        ]
    }
}
```

**Comment by dugite-code** [comment]
I'm able to reproduce your issue in the testing tab the config should look like this:
```json
{
   "type": "xpath",
   "xpath": "div[contains(@class, 'id-article-body')]"
}
```

Please exclude the url match section when testing. Related enhancement issue: https://github.com/feediron/ttrss_plugin-feediron/issues/159
