### ISSUE TITLE
PHP8-support as TT-RSS moved to PHP8 recently

### ISSUE THREAD

**Issue by meyca** [feediron/ttrss_plugin-feediron#166]
# Expected Behavior

With TT-RSS default setup having moved to PHP8, I would expect the Plugin to also support PHP8. 

# Current Behavior

Currently there are "Undefined array key" warnings in the TT-RSS logs.

## Steps to Reproduce

Use latest docker-compose TT-RSS setup from <https://git.tt-rss.org/fox/ttrss-docker-compose/src/branch/master> and install feediron into ./plugins.local

Once feeds are updated log warnings are likely to occur.

# Failure Information (for bugs)

example logs:
```
plugins/af_readability/vendor/andreskrey/Readability/Readability.php:199
usort():** Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero
```

```
plugins.local/feediron/init.php:575 
Undefined array key "modify"
```

**Comment by dugite-code** [comment]
For readability I just have to update the pinned version, and it looks like is_array has been deprecated

https://php.watch/versions/8.0/deprecated-reflectionparameter-methods

**Comment by dugite-code** [comment]
So readability.php hasn't received a new release recently however I think I've fixed the is_array issue in feediron, I just haven't been able to test it yet.

https://github.com/feediron/ttrss_plugin-feediron/tree/php8_dev

**Comment by dugite-code** [comment]
Ok I've done a bit of testing, I'm not seeing any issues with Readbility myself, perhaps I opened the upstream issue a bit early

as for the `Undefined array key` warnings, PHP 8 apparently switched this from a Notice event to a Warning event. Everything really should still work fine. I'm going to make *all* the array tests more explicit to avoid this warning

**Comment by dugite-code** [comment]
I have merged a number of php8 fixes into master

**Comment by meyca** [comment]
oh, there is one more thing ;-)
