### ISSUE TITLE
ReferenceError: Ajax is not defined

### ISSUE THREAD

**Issue by trockenasche** [feediron/ttrss_plugin-feediron#169]
# Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

# Expected Behavior

Do any configuration inside feediron.

# Current Behavior

Saving, adding and testing result to the popup error message
`ReferenceError: Ajax is not defined`
Unfortunately there is no more information to find in the popup.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. fresh tt-rss install from https://git.tt-rss.org/fox/ttrss-docker-compose.git
2. fresh install of this plugin
3. try to set it up

# Failure Information (for bugs)

<details>
<summary>Failure Logs</summary>

```
E_WARNING (2) | plugins.local/feediron/preftab/fi_pref_tab.php:44 | foreach() argument must be of type array\|object, null given 1. plugins.local/feediron/preftab/fi_pref_tab.php(44): ttrss_error_handler(2, foreach() argument must be of type array\|object, null given, plugins.local/feediron/preftab/fi_pref_tab.php, 44) 2. plugins.local/feediron/init.php(618): get_pref_tab(, ) 3. backend.php(131): index()

E_USER_WARNING (512) | client-js:tt-rss-layer.js?1613849410 line 8 > Function:6 | ReferenceError: Ajax is not defined anonymous@https://example.com/tt-rss/lib/dojo/tt-rss-layer.js?1613849410 line 8 > Function:6:4 _onSubmit@https://example.com/tt-rss/lib/dojo/tt-rss-layer.js?1613849410:8:238947 hitch/ 
```
</details>

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Ubuntu 20.04
* TTRSS version/git version: v21.02-d6de021ae
* PHP version: 8.0.2

**Comment by dugite-code** [comment]
Ok so it looks like Fox removed the old Ajax requests. Give the latest master a go it should be fixed now

**Comment by trockenasche** [comment]
Thanks, it's working now!
