### ISSUE TITLE
`Undefined index: plugin_data`  since tt-rss upgrade

### ISSUE THREAD

**Issue by symphorien** [feediron/ttrss_plugin-feediron#174]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

No errors in update daemon log.

# Current Behavior

```
│2021-07-03T16:09:07.472 1825955636476 tt-rss.service php[2449707] INFO [tt-rss] E_NOTICE (8) (plugins.local/feediron/init.php:92) Undefined index: plugin_data                                     │
│2021-07-03T16:09:07.474 1825955638659 tt-rss.service php[2449707] INFO [tt-rss] E_NOTICE (8) (plugins.local/feediron/init.php:142) Undefined index: owner_id                                       │
│2021-07-03T16:09:07.475 1825955638925 tt-rss.service php[2449707] INFO [tt-rss] E_NOTICE (8) (plugins.local/feediron/init.php:142) Undefined index: plugin_data
```

## Steps to Reproduce

Feediron works correctly with tt-rss revision 6d8f2221b82b6a31becbeed8baf5e05ad9e053fe
It started to fail when I upgraded to cd26dbe64c9b14418f0b2d826a38a35c6bf8a270

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: NixOS 21.05
* TTRSS version/git version: see above
* PHP version: 7.4

**Comment by dugite-code** [comment]
I'm not able to re-produce this issue. That said that looks like some legacy fallback code that shouldn't be running on the latest version.

It should be safe to delete these lines from your feediron init.php: https://github.com/feediron/ttrss_plugin-feediron/blob/41d4bcdc499718b2157b6003ef04261842450dd5/init.php#L90-L99


I'll have to go through and remove all of this fallback code as I don't plan to support anything other than the latest versions

**Comment by symphorien** [comment]
> that shouldn't be running on the latest version.

the latest version of what ? I'm on revision  41d4bcdc499718b2157b6003ef04261842450dd5 of feediron, which is current master, and my revision of tt-rss is from 2021-06-21 which is far from old.

**Comment by dugite-code** [comment]
I was referring to the latest version of both TT-RSS and Feediron. I'm not 100% farmiliar with the older versions of TT-RSS but it looks like this is old code that allows very old versions of TT-RSS to know if it's seen an article or not. This is no longer needed as TT-RSS nowdays hashes the article before it is filtered by Feediron.

I take it you are running bare metal and not in a docker container? There may be a hickup with the version checking that's allowing this code to run when it shouldn't

**Comment by symphorien** [comment]
Thanks it was indeed a packaging problem where get_version() would fail. Thanks for the pointer !
