### ISSUE TITLE
No type defined! error

### ISSUE THREAD

**Issue by ronajon** [feediron/ttrss_plugin-feediron#185]
running tt-rss 	v22.12-fb4bc26 in a docker environment. 

testing https://xkcd.com/rss.xml with configuration below gives an error "No type defined!"
i followed all steps to install the plugin within he docker 

```
{
    "xkcd.com": {
        "type": "xpath",
        "xpath": [
            "div[contains(@id,'comic')]",
            "div[contains(@id,'comic')]\/\/img\/@title"
        ],
        "join_element": "<p>"
    },
    "xkcd.com_orig": {
        "type": "xpath",
        "xpath": [
            "div[contains(@id,'comic')]",
            "div[contains(@id,'comic')]\/\/img\/@title"
        ],
        "join_element": "<p>"
    }
}
```

**Comment by dugite-code** [comment]
With the testing window you can't use the url element in the config. Additional it will only accept a single config at a time

eg:

```json
{
        "type": "xpath",
        "xpath": [
            "div[contains(@id,'comic')]",
            "div[contains(@id,'comic')]\/\/img\/@title"
        ],
        "join_element": "<p>"
    }
```

Also do not use the https://xkcd.com/rss.xml url when testing, you need to use a direct article url like https://xkcd.com/2724/

![image](https://user-images.githubusercontent.com/12742064/212582340-816aeac0-9c81-4e9b-9e16-89d92929a192.png)

**Comment by ronajon** [comment]
thx, that solved my issue
