### ISSUE TITLE
Readme file installation instructions are outdated

### ISSUE THREAD

**Issue by iacchi** [feediron/ttrss_plugin-feediron#186]
As per title, in the file it currently reads, in the second line of the cli instructions to give:

`git clone git://github.com/m42e/ttrss_plugin-feediron.git plugins.local/feediron`

however it should read:

`git clone https://github.com/feediron/ttrss_plugin-feediron.git plugins.local/feediron`

**Comment by dugite-code** [comment]
Oh wow that's a quite old slip up. I'll also add installing via the GUI
