### ISSUE TITLE
Multiple PHP "undefined" warnings

### ISSUE THREAD

**Issue by benfishbus** [feediron/ttrss_plugin-feediron#189]
# Expected Behavior
Please describe the behavior you are expecting

No/minimal warning messages logged by tt-rss about FeedIron.

# Current Behavior
What is the current behavior?

Logs contain various "undefined array key" and "undefined variable" warnings stemming from FeedIron.

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

Refresh any feed

# Failure Information (for bugs)
Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

<details>
<summary>Failure Logs</summary>

```
Undefined variable $tags
1. plugins. Local/feediron/filters/fi_mod_tags_xpath/init.php(27): ttrss_error_handler(Undefined variable $tags, plugins.local/feediron/filters/fi_mod_tags_xpath/init.php)

Undefined array key "debug"
1. plugins. Local/feediron/filters/fi_mod_all_xpath/init.php(8): ttrss_error_handler(Undefined array key "debug", plugins.local/feediron/filters/fi_mod_all_xpath/init.php)

Undefined array key "replace-tags"
1. plugins. Local/feediron/init.php(105): ttrss_error_handler(Undefined array key "replace-tags", plugins.local/feediron/init.php)

Undefined array key 0
1. plugins. Local/feediron/filters/fi_mod_tags_xpath/init.php(23): ttrss_error_handler(Undefined array key 0, plugins.local/feediron/filters/fi_mod_tags_xpath/init.php)

```
</details>

## Context
Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:  Docker
* TTRSS version/git version:  v23.04-fd684da
* PHP version:
* Feediron Configuration:  extensive...

```json
Paste Configuration here
```

**Comment by dugite-code** [comment]
I think there is a few separate things happening here.
1. Undefined variable $tags
    * The tags are clearly not being found so the variable isn't being set here
2. Undefined array key "debug"
    * The debug setting being set by default to false, I'll have to double check this code, but I'm not seeing this in my setup. Do you have the config option debug set in your config?
    * This is the `fi_mod_all_xpath` filter which I still treat as a bit of an alpha filter.
3. Undefined array key "replace-tags"
    * Looks like the $NewContent['replace-tags'] should be explicitly set false [https://github.com/feediron/ttrss_plugin-feediron/blob/56ee77369873f09880d9645186718e22f8e0b1c8/init.php#L213](init.php#L213)
4. Undefined array key 0
    * I need to revisit this it's was a quick and dirty error check.

**Comment by dugite-code** [comment]
Are you able to try the fixes on https://github.com/feediron/ttrss_plugin-feediron/commit/8a5093dc48117b5320f553f3c487791313a9b26f in the dev branch. This should address 1,3 and 4

**Comment by dugite-code** [comment]
I've merged the changes I've done into the master branch. I'm still not sure about the Undefined array key "debug" issue
