### ISSUE TITLE
Is it possible to use the original (article) url in modify rules?

### ISSUE THREAD

**Issue by rookiejet** [feediron/ttrss_plugin-feediron#194]
I would like to do something like
```
"replace": [
    "src=\"$url/"
]
```
or in readability `"relativeurl": "$url\/"` where $url is the original article url.

**Comment by dugite-code** [comment]
Currently no, but it's actually an excellent idea for an enhancement. Getting all the parts from [parse_url](https://www.php.net/manual/en/function.parse-url.php) is certainly simple enough. Evaluating the variables in the replace function might need a bit of noodling though, I know you can use curly brackets in an echo around a variable but not sure in preg_replace.

**Comment by rookiejet** [comment]
Thank you @monofox and @dugite-code! I've tested it and it works great.
