### ISSUE TITLE
Uninitialized config null value incorrectly handled

### ISSUE THREAD

**Issue by entekadesign** [feediron/ttrss_plugin-feediron#195]
# Expected Behavior

* In Feediron tab in TT-RSS preferences: pressing "Add" button should populate configuration with a recipe

# Current Behavior

* Configuration field contains "undefined"

# Failure Information (for bugs)

* Log: 

`PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/html/tt-rss/plugins.local/feediron/preftab/fi_pref_tab.php on line 44`

* Following form data payload sent to TT-RSS Backend.php:

`op=pluginhandler&method=add&plugin=feediron&addrecipe=https%3A%2F%2Fapi.github.com%2Frepos%2Ffeediron%2Ffeediron-recipes%2Fcontents%2Fgeneral%2Fabgeordnetenwatch.de.json%3Fref%3Dmaster&csrf_token=29b175bd0bfceac378895b04c123534d`

* Backend response:

`{"error":{"code":"E_UNKNOWN_METHOD","params":{"info":"UNKNOWN:pluginhandler->add"}}}` 

* Conclusion: "Add" method defined in Feediron's "init.php" is not available to TT-RSS's "pluginhandler.php". Log suggests Ironfeed config is not loading.

* N.B.: behavior exhibited on fresh install, tested in a few major browsers without plugins

* Operating System: Docker on Linux on Synology NAS
* TTRSS version/git version: v23.11-ff4248b0
* PHP version: 8.2.10 (on TT-RSS docker container)
* Feediron version: v1.32
* Feediron Configuration:

```json
{}
```

**Comment by dugite-code** [comment]
@entekadesign Ah yes, I was going to post a bug as I had this reported over on community.tt-rss.org

It's the empty config, just manually add `{}` then save the config an it should work. We need to add a catch to deal with fully `null` configs

**Comment by dugite-code** [comment]
I just added a quick check in the [nullconf](https://github.com/feediron/ttrss_plugin-feediron/tree/nullconf) branch I'll try check it today but if you get around to it first let me know how it goes

**Comment by entekadesign** [comment]
I updated the plugin on the persistent volume with the "init.php" from the nullconf branch. Unfortunately, that didn't seem to work. Maybe the string literal '{}' isn't getting added at the right point. I don't have the setup right now to do a proper troubleshoot.

**Comment by dugite-code** [comment]
Ok, I'll have a tinker when I can get around to setting up a new use on my instance.

**Comment by dugite-code** [comment]
It looks like I may have misdiagnosed the issue see: pull #196 Try the latest master and let me know if that fixes your issue.

**Comment by entekadesign** [comment]
That was it. I should have noticed that. Ugh. Thanks!

**Comment by dugite-code** [comment]
That's ok I missed that in the Logs and the post on the forum as well.
