### ISSUE TITLE
Getting The Fetched Feed?

### ISSUE THREAD

**Issue by teamcoltra** [feediron/ttrss_plugin-feediron#197]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ *] I am running the latest version
- [* ] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

# Expected Behavior

I'm not fully sure.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Debian 11
* TTRSS version/git version: 24.02-373a2fec3 
* PHP version: 8.2

I don't know if I'm dumb, missing something, or something isn't working. 

What I was hoping (and what it sounds like I'm getting) was for this plugin to fetch the article from the URL and bring in the full text even if the RSS feed only has the default snippit. 

I added in the configurations for all the websites I have that you have premade. Yet, none of them seem to be pulling the article. At least not by default. Is there a button I'm supposed to press? A setting to enable Feediron for that specific feed?  When I do the test it works. 

Also can I have a catch-all regex in my config? Like:

```

  "(.*)":{
    "type":"readability"
  },
```

So that for everything that doesn't already have xpaths defined then it will just use readability without needing to add a setting for each url? 

I should probably just get the plugin working before worrying about extra configs though :)

**Comment by dugite-code** [comment]
> fetch the article from the URL and bring in the full text even if the RSS feed only has the default snippit.
This is the expected behavior. There may have been changes on the TTRSS side. Turns out my instance is was no longer able to pull the docker container for some reason. I'll fix my instance and try to confirm if feed iron is running as expected.

The URL matching uses PHP's `strpos` and only matches strings, unfortunately no regex.

**Comment by dugite-code** [comment]
Ok I fixed my docker containers and everything looks to be working fine on `v24.02-373a2fec`

* Could you provide your config output. 
* [Enable debugging](https://github.com/feediron/ttrss_plugin-feediron?tab=readme-ov-file#debug---debugbool)
* Check the Event log under the system tab in preferences.
* (This my sound silly) Did you save your config after adding the rules to the main config?
