### ISSUE TITLE
Help in setting up a filter config

### ISSUE THREAD

**Issue by mariomaz87** [feediron/ttrss_plugin-feediron#198]
# Expected Behavior

Hi, sorry to open an issue even if this is more a request for help, I don't think it's an actual bug.
I have a website with many feeds like this: https://www.ilfoglio.it/economia/rss.xml
I want to create a filter in feediron to discard articles when the linked articles contains the words "abbonati per" in the contents.

# Current Behavior

Using the following config, I get no syntax error but both the test and the actual feeds are still displaying articles I want to omit:

```json
{
    "ilfoglio.it": {
        "filtering": {
            "rules": "xpath",
            "rule": {
                "match": "(.\/\/link)[contains(., 'abbonati per')]",
                "action": "omit"
            }
        }
    }
}
```

## Steps to Reproduce

Insert the config in feediron plugin.

## Context

* Operating System: TTRSS running in docker, latest version

**Comment by dugite-code** [comment]
Your config isn't a valid config, the syntax check is extremely simple and only verifies you have entered valid json. Feediron fetches the article full-text and formats it. It has no ability to perform any actions like dropping an article.

That said as part of the full-text process you could [set an article tag](https://github.com/feediron/ttrss_plugin-feediron?tab=readme-ov-file#tags-filter) and then use the TT-RSS [content filters](https://tt-rss.org/wiki/ContentFilters) (preferences -> Filters Tab) to drop that tag.

A rough example:
```json
{
  "type": "xpath",
  "xpath": [
    "section[@class='article'"
  ],
  "tags": {
    "type": "xpath",
    "replace-tags": false,
    "xpath": [
      "p[contains(text(),'abbonati per']"
    ]
  }
}
```

**Comment by mariomaz87** [comment]
Thanks for the feedback. I read the documentation and your reply. Can I use the tags with the Readability type? Because without using Readability I'm not able to intercept the contents of the article.
I'm trying with this:

`{
    "ilfoglio.it": {
        "type": "readability",
        "tags": {
            "type": "search",
            "pattern": [
                "\/abbonati\/"
            ],
            "match": [
                "!paywall"
            ]
        }
    }
}`

I don't know why it works only using the "!" match. Using this config it tags the article Paywall even if the word "abbonati" is in the result section of the testing page. If I use "paywall" instead of "!paywall" the test does not run.

Thanks!

**Comment by dugite-code** [comment]
Great to see you got it working, hope that all works out for you.
