### ISSUE TITLE
Recipes are not followed when updating feeds

### ISSUE THREAD

**Issue by nikolas-n** [feediron/ttrss_plugin-feediron#205]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Websites should follow feediron recipes.

# Current Behavior

None of the recipes I have in my configuration file works. When I use the testing console in preferences, any/all recipes work. However, when the feeds are updated, no recipe is applied. Before updating feediron+tt-rss everything was working properly.

Edit: I'm adding some more info that may help:

When I right click on the feed and select Debug Feed, then in the opening page, if I select Force refetch, the feed is updated correctly, and the rules are applied. 

## Steps to Reproduce

1. Upgrade feediron to latest version
2. Upgrade tt-rss to latest version
3. Let ttrss update feeds
4. No feed follows the recipes determined

* Operating System: Debian 12.7
* TTRSS version/git version: TT-RSS git commit: 1fb202b258c751cb4e64bc38603c67263cc45959
* PHP version: 7.4.33
* Feediron Configuration:

```
{"pitsirikos.net": {
        "type": "xpath",
        "xpath": "div[@class='entry-inner']"
    }}
```

**Comment by dugite-code** [comment]
Sorry, I'm unable to re-produce your issue. the configuration is working well on my docker based install.

I do note you are on a very old EOL PHP version. There has been a fair amount of changes in both TTRSS and Feediron for PHP8 so this may be part of the issue. Consider trying the docker container to see if you can re-produce the issue.

**Comment by nikolas-n** [comment]
Thanks a lot for replying! I just noticed that I hadn't added the correct version, I recently updated to 8.2, if that changes anything.
I'll try the docker container as you suggested and see if i can reproduce the issue.
Thanks!
