### ISSUE TITLE
Text after iframes is dropped while testing

### ISSUE THREAD

**Issue by cwmke** [feediron/ttrss_plugin-feediron#22]
Inside of the preferences, showing the result inside of the testing pane, I have found that if a video is embedded in the middle of the body of text, the filtered result provides the text, then the iframe with the video, but cuts off the text below the iframe.  

This does not effect the article filtering by tt-rss.  So the end result is still perfect, this is just a problem while testing.

An example is provided below.  With my configuration, and link that demonstrates the problem.  Thanks for any help.

http://www.geek.com/news/tv-muppets-live-action-winnie-the-pooh-and-new-full-house-are-coming-1619592/

{
    "type": "xpath",
    "xpath": "div[@class='articleinfo']"
}

**Comment by thomo5000** [comment]
Self-closing tags don't seem to work properly. Don't know enough to debug the actual issue, but a workaround is pretty easy:

 ```
"modify": [
  {
    "type": "regex",
    "pattern": "(<iframe(.*?)>)",
    "replace": "<iframe $1></iframe>"
  }
]
```

**Comment by dugite-code** [comment]
This might be fixed by using html tidy. It's currently only in the readability functions
