### ISSUE TITLE
PHP fatal error on init.php line 502

### ISSUE THREAD

**Issue by cwmke** [feediron/ttrss_plugin-feediron#24]
I'm getting an error with one of my feeds that states, "PHP Fatal error:  Call to a member function saveXML() on null in {path}/plugins/feediron/init.php on line 502.  

I've been having trouble getting all of my feeds to update.  Several seem to be ignored for days if I don't get them manually.

The feed that comes up as a problem is http://feeds.feedburner.com/chinafile/All and below is my config for that feed.

Any help will be greatly appreciated.  Thanks for your time.

```
"chinafile.com": {
    "type": "xpath",
    "xpath": [
        "div[@class='visual-image-box']/..",
        "div[contains(@class, 'field-name-body')]"
    ],
    "cleanup": [
        "script"
    ]
}
```

**Comment by m42e** [comment]
Well, I see, there should be more tests, I'm a bit busy at the moment, but I keep that in mind.

**Comment by cwmke** [comment]
I just want to update with more specific information.  Below seems to be the continual errors I get.  I had a rule at the end that marked "http" to readability to help with hackernews that I removed.  I'm hoping that will resolve the problems with feeds not refreshing.  There's no rush though since I'm sure you're busy.  Thanks.

Call to a member function saveXML() on null
plugins/feediron/init.php:522	

plugins/feediron/init.php:522   Couldn't fetch DOMElement. Node no longer exists
plugins/feediron/init.php:529   Invalid argument supplied for foreach()
plugins/feediron/init.php:528   Couldn't fetch DOMElement. Node no longer exists
plugins/feediron/init.php:195   array_key_exists() expects parameter 2 to be array, null given

**Comment by dugite-code** [comment]
To add my experience with this issue to the mix:

I was having a similar problem with the guardian open source category RSS feed.

I think it was because using an xpath on the article that would return a blank/mangled node on the video links. I ended up using readability instead

**Comment by cwmke** [comment]
Thanks for the suggestion.  I just went through my log and found the feeds that I think are the issue.  I'll try to clean up the xpath and hopefully that does the trick.  I'll see if it locks up again over the next week.  Thanks.

**Comment by dugite-code** [comment]
And somehow I deleted my comment. In case anyone else wants the info:

I had a similar issue with the guardian open source category rrs feed.

I think it had to do with my xpath I used for the articles not quite working on the video posts and returning a blank/mangled node.

I ended up having to switch to readability on that feed because I couldn't find an xpath that would work for both article and video posts

**Comment by cwmke** [comment]
I'm adding some more info since I recently switched back to tt-rss and am still having this issue.  I'm manually running the updates now to see where the snags occur and it appears to be an issue with images or videos Listed above the article's text.

For example, normally I only want the top photo and the article text so my xpath will be as follows.
```
"div[@class='MainImg']",
"article"
```

When I reverse this and put the image at the bottom, this resolves the issues (although not ideally).  In some cases, I have had to remove the images.  I'm not sure if this is helpful but I just thought I would add my observations.  Let me know if you want any other information.

**Comment by cwmke** [comment]
I found that my earlier statement also did not fully resolve the issues.  I ended up altering all of my rules so that they use less specific xpath options.  Although it's not my favourite solution since it requires adding more cleanup options, it removed all of the errors and my feeds are once again updating normally.

**Comment by einsweniger** [comment]
Since I don't know what's wrong here, I "fixed" it by catching and logging the exception.
So at least my feeds will not stop syncing :D
[feediron.txt](https://github.com/m42e/ttrss_plugin-feediron/files/743016/feediron.txt)

**Comment by einsweniger** [comment]
As a little update: I guess the cleanup statement is the culprit.
When my xpath does not match any element, the cleanup tries to search in a non-existant DOM.
At least, that happened when I added a new recipe today.
