### ISSUE TITLE
Assistance with nytimes.com

### ISSUE THREAD

**Issue by cwmke** [feediron/ttrss_plugin-feediron#27]
I've been trying to figure out how to pull anything from the nytimes site but the result is always blank, even when using readability.  Do you have any ideas?  Thanks.

http://www.nytimes.com/2015/04/24/us/politics/pentagon-announces-new-cyberwarfare-strategy.html

**Comment by m42e** [comment]
I think the content is not delivered within the page, it is loaded somehow (maybe websockets) after the page load. There is no way to get the content at the moment. And I cannot imagine a proper way to do so.

**Comment by cwmke** [comment]
Fair enough.  Thanks for looking into it, should I go ahead and close
this or leave it open for the future?
