### ISSUE TITLE
set tags with xpath (request)

### ISSUE THREAD

**Issue by thomo5000** [feediron/ttrss_plugin-feediron#40]
I have a few feeds that don't include tags but they are included when you view the linked page. 

It would be awesome to have an option to scrape tags using XPATH as well. Is this feasible?

For example huffingtonpost.com uses div[@class = 'entry-tags-component']

Cheers

**Comment by m42e** [comment]
Sounds nice to me.

**Comment by dugite-code** [comment]
In progress in the [tags branch](https://github.com/feediron/ttrss_plugin-feediron/tree/tags)

**Comment by dugite-code** [comment]
Calling on Testers for the Tags branch.

Example config:
```json
{
    "type": "xpath",
    "xpath": "div[@id='commits_bucket']",
    "tag-xpath": [
        "a[contains(@class,'commit-auhor')]"
    ],
    "replace-tags": true
}
```

**Comment by dugite-code** [comment]
Needs allitems #86 to be included to make it useful

**Comment by dugite-code** [comment]
Proposed change to wrap tag functions to neaten up the config

```json
{
    "type": "xpath",
    "xpath": "div[@id='commits_bucket']",
    "tags": {
        "type": "xpath",
        "xpath": [
            "p[@class='topics']"
        ],
        "cleanup": [
            "strong"
        ],
        "modify": [
            {
                "type": "replace",
                "search": "-",
                "replace": " "
            }
        ]
    }
}
```

**Comment by dugite-code** [comment]
I've added two new types to the tag option search and regex. Regex returns matches where search simply searches (using regex) and returns a pre-defined match if found

```json
    "tags": {
        "type": "regex",
        "pattern": [
            "\/August\/"
        ],
        "index":0
}
```
```json
    "tags": {
        "type": "search",
        "pattern": [
            "\/August\/"
        ],
        "match": [
            "strong"
        ]
    }
```

**Comment by dugite-code** [comment]
Tag searches can now also be inverted using `!` in front of the match if the pattern *IS NOT FOUND* the tag is returned

```json
    "tags": {
        "type": "search",
        "pattern": [
            "\/August\/"
        ],
        "match": [
            "!strong"
        ]
    }
```
