### ISSUE TITLE
Unable to get RockPaperShotgun to work

### ISSUE THREAD

**Issue by catatonik** [feediron/ttrss_plugin-feediron#48]
Hi There,

I'm using the below block, and url, however it still shows the footer & sidebar. Can anyone help properly filter these out please?

Thanks!

config:
{
    "type": "xpath",
    "xpath": "div[@id='content']\/div[@class='content']\/div[contains(@class, 'block')]",
    "cleanup": [
        "div[@id='header']\/div[@class='header-content']",
        "div[@class='header-items']",
        "div[@id='footer']",
        "ul[@id='sidebar']"
    ]
}

test url:
http://www.rockpapershotgun.com/2016/01/04/smite-world-championship-2016-everything-you-need-to-know/

**Comment by dugite-code** [comment]
Seems to me you are attempting to grab to much and then scrub it clean. I always prefer to do a little more targeted xpath and then the minimal amount of cleanup. Firefox's inspect element is a great way to fine the class name of content you actually want.

```
{
    "type": "xpath",
    "xpath": "div[@class='post-inner']",
    "cleanup": [
        "nav"
    ]
}
```

**Comment by catatonik** [comment]
excellent, thank you!
