### ISSUE TITLE
Testing works but feed does not.

### ISSUE THREAD

**Issue by bryanlyon** [feediron/ttrss_plugin-feediron#52]
When testing the following rule for lifehacker or gizmodo it works perfectly.  However, when run against the actual feed (and I am waiting for new entries to come in), there is absolutely no effect on the feed content.

{
    "type": "xpath",
    "xpath": [
        "h1[contains(@class,'headline')]",
        "div[contains(@class,'meta__byline')]",
        "div[contains(@class,'post-content')]"
    ],
    "join_element": "<p>",
    "cleanup": [
        "div[contains(@class,'taboola')]"
    ],
    "force_charset": "utf-8"
}

**Comment by dugite-code** [comment]
Your posted config no longer works so I threw this together. Are you still experiencing issues?

The cleanup is usually to blame in these cases.

```json
{
    "type": "xpath",
    "xpath": [
        "h1[contains(@class,'page-title')]",
        "div[contains(@class,'meta__author')]",
        "article[contains(@class,'article-content')]"
    ],
    "join_element": "<br>",
    "cleanup": "script"
}
```

**Comment by ail1020** [comment]
I'm having a similar issue. I've tried the following recipe without success. It works in the testing tab, but additional images don't show up in the feed. A good example URL is this: https://lifehacker.com/every-2020-democratic-candidates-plan-to-end-the-hiv-ai-1838036853

```
{
    "type": "xpath",
    "xpath": [
        "h1[contains(@class,'entry-title')]",
        "div[contains(@class,' author ')]",
        "img[contains(@class,'lazyload')]",
        "div[contains(@class,'post-content')]"
    ],
    "modify": [
        {
            "type": "regex",
            "pattern": "<img\\ssrc=\"data.*?\".*?data-srcset=\"(.*?)\\s2x,\\s.*?\".*?\/>",
            "replace": "img src=\"$1\" class=\"lazyload ls-lazy-image-tag\"\/"
        }
    ],
    "cleanup": [
        "hr",
        "aside[contains(@class,'inset--story')]",
        "div[contains(@class,'instream-native-video')]",
        "img[contains(@src,'assets\/images\/logos\/placeholders')]"
    ],
    "join_element": "<br>"
}
```

**Comment by dugite-code** [comment]
@ail1020 missing images are typically caused by the `data-srcset` and `srcset` attributes. It also could be Hot-linking protections causing the image to be unable to load

Unfortunately the lifehacker pages are very complex and js heavy so every time there is a change a fair amount of work is required to get it all working again. I'll try have a look at some point to make sure it's not a bug
