### ISSUE TITLE
golem.de not working

### ISSUE THREAD

**Issue by christianbur** [feediron/ttrss_plugin-feediron#54]
Hello, 
can anyone fix the recipe for golem.de, because it does not work anymore.
I can not find any "rss.feedsportal.com" with "golem0Bde0C" in the Feed (http://rss.golem.de/rss.php?feed=ATOM1.0) there are only "www.golem.de/news" URLs.

The articles between  <article>...</article>

**Comment by radlerandi** [comment]
everything changes from time to time. better learn to adjust recipes.

i use this since some weeks and it works good for me.

    "golem.de": {
        "type": "xpath",
        "xpath": "article",
        "multipage": {
            "xpath": "ol\/li\/a[contains(@id, 'atoc_')]",
            "append": true
        },
        "reformat": [
            {
                "type": "replace",
                "search": "-rss.html",
                "replace": ".html"
            }
        ],
        "cleanup": [
            "a[@class='golem-gallery2-nojs']",
            "ol[@id='list-jtoc']",
            "table[@id='table-jtoc']",
            "div[@class='htmlinline']",
            "div[@class='iqadcenter']",
            "div[@id='iqadtile4']"
        ]
    }
