### ISSUE TITLE
Error with tt-rss v16.8 (f04b12d)

### ISSUE THREAD

**Issue by DarkPreacher** [feediron/ttrss_plugin-feediron#60]
I just cloned Feediron from github to my plugins.local dir, and got this in Preferences → Plugins from XDebug.
```
Fatal error: Cannot redeclare define_default() (previously declared in \rss\include\functions.php:39) in \rss\include\functions.php on line 41
Call Stack
#	Time	Memory	Function	Location
1	0.0004	400024	{main}( )	...\backend.php:0
2	0.0672	2695064	Pref_Prefs->index( )	...\backend.php:123
3	0.0749	2806952	PluginHost->load_all( )	...\prefs.php:753
4	0.0780	2811840	PluginHost->load( )	...\pluginhost.php:145
5	0.0863	3349176	require_once( '\rss\plugins.local\feediron\init.php' )	...\pluginhost.php:168
```
I'll appreciate any help.

**Comment by m42e** [comment]
Looks like the include of "Functions.php" causes the error. I think all the includes should be changed to a include_once or require_once.

**Comment by DarkPreacher** [comment]
Yep, changing all `include` to `include_once` worked, thank you!

**Comment by mightymt** [comment]
@m42e Thanks for the fix.

I recently experienced this problem while trying to set up tt-rss on my local machine (Windows 10, latest version of XAMPP with PHP 7.2.4). However on my hosted webspace (Linux with PHP 7.0.29) it works fine without modification.
