### ISSUE TITLE
Class 'Feediron_Json' not found

### ISSUE THREAD

**Issue by alex9434** [feediron/ttrss_plugin-feediron#61]
Dear all,

I get the error message Class 'Feediron_Json' not found when I start the plugin feediron. The file Json .php is in the directory plugins/feediron. Any idea?

Regards,
Alex
----
E_ERROR (1)	plugins/feediron/init.php:655	Class 'Feediron_Json' not found	admin	13:55
E_USER_WARNING (512)	plugins/feediron/Logger.php:33	last error: 0	admin	13:55
E_USER_WARNING (512)	plugins/feediron/Logger.php:33	{ "name": "The Oatmeal", "author": "Markus Birth", "stamp": 1371635271, "feed": "http://theoatmeal.com/feed/rss", "match": "oatmeal", "config": { "type": "xpath", "xpath": "div[@id='comic']", "cleanup": [ "div[@id='content_footer2']" ] } }	admin	13:55
E_USER_WARNING (512)	plugins/feediron/Logger.php:33	Recipe content: ewogICAgIm5hbWUiOiAiVGhlIE9hdG1lYWwiLAogICAgImF1dGhvciI6ICJNYXJrdXMgQmlydGgiLAogICAgInN0YW1wIjogMTM3MTYzNTI3MSwKICAgICJmZWVkIjogImh0dHA6Ly90aGVvYXRtZWFsLmNvbS9mZWVkL3JzcyIsCiAgICAibWF0Y2giOiAib2F0bWVhbCIsCiAgICAiY29uZmlnIjogewogICAgICAgICJ0eXBlIjogInhwYXRoIiwKICAgICAgICAieHBhdGgiOiAiZGl2W0BpZD0nY29taWMnXSIsCiAgICAgICAgImNsZWFudXAiOiBbICJkaXZbQGlkPSdjb250ZW50X2Zvb3RlcjInXSIgXQogICAgfQp9Cg==	admin	13:55
E_USER_WARNING (512)	plugins/feediron/Logger.php:33	Recipe content: {"name":"theoatmeal.json","path":"mods/theoatmeal.json","sha":"418ce1086c495da67c86dcfe3b99e5cbe685d906","size":292,"url":"https://api.github.com/repos/mbirth/ttrss_plugin-af_feedmod/contents/mods/theoatmeal.json?ref=master","html_url":"https://github.com/mbirth/ttrss_plugin-af_feedmod/blob/master/mods/theoatmeal.json","git_url":"https://api.github.com/repos/mbirth/ttrss_plugin-af_feedmod/git/blobs/418ce1086c495da67c86dcfe3b99e5cbe685d906","download_url":"https://raw.githubusercontent.com/mbirth/ttrss_plugin-af_feedmod/master/mods/theoatmeal.json","type":"file","content":"ewogICAgIm5hbWUiOiAiVGhlIE9hdG1lYWwiLAogICAgImF1dGhvciI6ICJN\nYXJrdXMgQmlydGgiLAogICAgInN0YW1wIjogMTM3MTYzNTI3MSwKICAgICJm\nZWVkIjogImh0dHA6Ly90aGVvYXRtZWFsLmNvbS9mZWVkL3JzcyIsCiAgICAi\nbWF0Y2giOiAib2F0bWVhbCIsCiAgICAiY29uZmlnIjogewogICAgICAgICJ0\neXBlIjogInhwYXRoIiwKICAgICAgICAieHBhdGgiOiAiZGl2W0BpZD0nY29t\naWMnXSIsCiAgICAgICAgImNsZWFudXAiOiBbICJkaXZbQGlkPSdjb250ZW50\nX2Zvb3RlcjInXSIgXQogICAgfQp9Cg==\n","encoding":"base64","_links":{"self":"https://api.github.com/repos/mbirth/ttrss_plugin-af_feedmod/contents/mods/theoatmeal.json?ref=master","git":"https://api.github.com/repos/mbirth/ttrss_plugin-af_feedmod/git/blobs/418ce1086c495da67c86dcfe3b99e5cbe685d906","html":"https://github.com/mbirth/ttrss_plugin-af_feedmod/blob/master/mods/theoatmeal.json"}}	admin	13:55
E_USER_WARNING (512)	plugins/feediron/Logger.php:33	Recipe url: https://api.github.com/repos/mbirth/ttrss_plugin-af_feedmod/contents/mods/theoatmeal.json?ref=master	admin	13:55
E_USER_WARNING (512)	plugins/feediron/Logger.php:33	recipe: https://api.github.com/repos/mbirth/ttrss_plugin-af_feedmod/contents/mods/theoatmeal.json?ref=master	admin	13:55
E_USER_WARNING (512)	plugins/feediron/Logger.php:33	No Config found

**Comment by dugite-code** [comment]
Well your error there mentions af_feedmod witch is a separate plugin.

How did you install Feediron?

What's your configuration look like?

Are there error's showing when testing or just in the system logs?
