### ISSUE TITLE
Configuration window fills up with spaces

### ISSUE THREAD

**Issue by cy8aer** [feediron/ttrss_plugin-feediron#62]
My actual git-version of feediron fills the configuration field with additional space lines between every line in the configuration with every saving of the configuration. Even reformating and repasting fills the field. Actual version used: 

 a909e9ee0cea72df7405a097623ec9910cf72f9d

![bildschirmfoto von 2017-02-14 09-34-50](https://cloud.githubusercontent.com/assets/578172/22921293/438c260e-f299-11e6-95a0-ba1adcb97834.png)

**Comment by cwmke** [comment]
I have the same issue with latest tt-rss, feediron and php 7.1.3-2.

**Comment by uusijani** [comment]
I make no guarantees this doesn't break something else, but for me it seems to work correctly if I make Feediron_Json::format() skip carriage returns:

    $ git diff
    diff --git a/Json.php b/Json.php
    index c988962..fc7f554 100644
    --- a/Json.php
    +++ b/Json.php
    @@ -8,6 +8,7 @@ class Feediron_Json{
                    $strLen      = strlen($json);
                    $indentStr   = '    ';
                    $newLine     = "\n";
    +               $cReturn     = "\r";
                    $prevChar    = '';
                    $outOfQuotes = true;
                    $currentline = 0;
    @@ -30,6 +31,9 @@ class Feediron_Json{
                                    $currentline++;
                                    continue;
                            }
    +                       if($char == $cReturn){
    +                               continue;
    +                       }
                            if($char == ' ' && $outOfQuotes){
                                    continue;
                            }

(Using PHP 5.6.30 here.)

**Comment by thomo5000** [comment]
Thanks @uusijani - confirming that fix works for me too using allitems branch + PHP 5.6.30.
