### ISSUE TITLE
Images not being rendered correctly

### ISSUE THREAD

**Issue by darrensimons** [feediron/ttrss_plugin-feediron#63]
I'm seeing an issue with images not being correctly parsed but I'm not 100% sure if the issue is with the plugin or with tt-rss.

I am using latest version of ttrss and feediron plugin via github requests (checked today).

Via FeedIron testing tab I get the correct results, but the result in ttrss excludes the image.  The image exclusion happens maybe 70% of the time for www.economist.com.

URL tested = http://www.economist.com/news/obituary/21717785-long-time-manager-new-yorks-hotel-chelsea-was-82-obituary-stanley-bard-died-february?fsrc=rss

JSON config:
{
    "type": "xpath",
    "xpath": "article | \/\/img[contains(@class,'component-image__img')]",
    "cleanup": "not_aside",
    "force_charset": "utf-8"
}

The result shows the image and then the text (the gap does not appear in the ttrss output but I don't know if this is relevant).  However, when I load this in ttrss the image does not appear.  Any thoughts?

**Comment by dugite-code** [comment]
I run into this issue often, the responsive image attribute `srcset` is to blame modifying it to `null` fixes the issue.

```
{
    "type": "xpath",
    "xpath": "article | \/\/img[contains(@Class,'component-image__img')]",
    "cleanup": "not_aside",
    "force_charset": "utf-8",
    "modify": [
        {
            "type": "replace",
            "search": [
                "srcset"
            ],
            "replace": [
                "null"
            ]
        }
    ]
}
```

**Comment by darrensimons** [comment]
Many thanks for this.  That has helped a lot, and I'm a bit annoyed for 
not spotting it before.

Kind regards,

Darren


On 09/04/2018 08:48, dugite-code wrote:
> |"type": "xpath", "xpath": "article | 
> \/\/img[contains(@Class,'component-image__img')]", "cleanup": 
> "not_aside", "force_charset": "utf-8", "modify": [ { "type": 
> "replace", "search": [ "srcset" ], "replace": [ "null" ] } ]|



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
