### ISSUE TITLE
"Cannot redeclare base64_img()" - All plugins disappear after install.

### ISSUE THREAD

**Issue by adamrabbit** [feediron/ttrss_plugin-feediron#66]
After installing this plugin and reloading tt-rss all the plugins from the preferences window disappear. 

The only error I see when reloading tt-rss is:
`E_ERROR (1)	include/Functions.php:2454	Cannot redeclare base64_img() (previously declared in /var/www/ttrss/include/functions.php:2454)`

I'm not quite sure how to fix that. Do anyone have an idea?

**Comment by dugite-code** [comment]
This could be related to #60
