### ISSUE TITLE
Lost characters from iso-8859-15 on UTF-8 system

### ISSUE THREAD

**Issue by xalabin** [feediron/ttrss_plugin-feediron#68]
With these config, on specific for a web and other general for use readability on all webs, when the web is on iso-8859-15, readability simply drops special characters, so thing like "camión" inserts on the database like "" camin"

{
  "elpais.com": { 
    "type": "xpath",
    "xpath": "article",
    "cleanup": ["button"]
  },
  ".": {
    "type": "readability"
  }
}

**Comment by xalabin** [comment]
If you want to usea readability method whit other than utf-8 webs, it's mandatory to put an undocuemented? conf in yout json.

{
"elpais.com": {
"type": "xpath",
"xpath": "article",
"cleanup": ["button"]
},
".": {
"type": "readability",
 "force_unicode": "1"
}
}

**Comment by dugite-code** [comment]
The force unicode option is "technically" documented as it's in the massive example config on the readme.

The Readme as it is needs a bit of a review and some rationalization.
