### ISSUE TITLE
Test fi_mod_all_xpath

### ISSUE THREAD

**Issue by dugite-code** [feediron/ttrss_plugin-feediron#86]
I've used the allitems option from the allitems branch in the past and found it very useful

- [x] It should be updated
- [x] bug checked
- [ ] Integrated with tags branch

**Comment by thomo5000** [comment]
I'm testing this now as my daily driver.

**Comment by dugite-code** [comment]
It should be noted this has been converted to an [experimental module](https://github.com/feediron/ttrss_plugin-feediron/tree/master/filters/fi_mod_all_xpath)
