### ISSUE TITLE
Uncaught PDOException: There is no active transaction in /var/www/tt-rss/classes/rssutils.php:1176

### ISSUE THREAD

**Issue by symphorien** [feediron/ttrss_plugin-feediron#87]
This is a reopening of https://github.com/feediron/ttrss_plugin-feediron/issues/78
Sometimes, feediron can cause:
```
Uncaught PDOException: There is no active transaction in /var/www/tt-rss/classes/rssutils.php:1176
```

These are the results of my investigations about the cause of this exception. I am not familiar with PHP so may need to be checked :)

Before the exception is raised, before this line https://git.tt-rss.org/fox/tt-rss/src/master/classes/rssutils.php#L754 `$pdo->inTransaction()` returns `true` and after this line it returns `false`.
Indeed the `pdo` instance is static and thus shared across the whole application. This suggests feediron is using the pdo to initiate a new transaction when this transaction https://git.tt-rss.org/fox/tt-rss/src/master/classes/rssutils.php#L754 is not commited. `PDO::beginTransaction` seems to be idempotent, and when feediron commits its own transaction, in fact it also commits the transaction begun in https://git.tt-rss.org/fox/tt-rss/src/master/classes/rssutils.php#L597. $pdo after https://git.tt-rss.org/fox/tt-rss/src/master/classes/rssutils.php#L754 is thus already commited and cannot be commited a second time.

The problem is that grepping for `Db::pdo` in feediron returns nothing. Adding a print statement to `DB::pdo()` seems to indicate that feediron causes uses or PDO through the logging mechanism. When logging is configured to be sql, any use of the ttrss logging mechanism by feediron will use the pdo and commit it.

This happens when debug is true in the feediron configuration, and when another error is caught, which misleads people into thinking the PDO error is caused by the other feediron error.

## Steps to Reproduce

* configure ttrss to log with sql
* apply this diff for the sake of simplicity:
```diff
diff --git a/init.php b/init.php
index 69995a5..0d79039 100644
--- a/init.php
+++ b/init.php
@@ -73,7 +73,16 @@ class Feediron extends Plugin implements IHandler
        function hook_article_filter($article)
        {
                Feediron_Logger::get()->set_log_level(0);
               if (($config = $this->getConfigSection($article['link'])) !== FALSE)
+                trigger_error("test", 512);
                {
                        if (version_compare(VERSION, '1.14.0', '<=')){
                                if (strpos($article['plugin_data'], $articleMarker) !== false)

```
* wait for feediron to be applied to a new article (for example remove and resubscribe to a feed)
The log will look like 
```
E_ERROR (1) | classes/rssutils.php:1180 | Uncaught PDOException: There is no active transaction in /usr/share/tt-rss/www/classes/rssutils.php:1180 Stack trace: #0 /usr/share/tt-rss/www/classes/rssutils.php(1180): PDO->commit() #1 /usr/share/tt-rss/www/update.php(417): RSSUtils::update_rss_feed('129') #2 {main}   thrown
E_USER_WARNING (512) | plugins/feediron/init.php:76 | test  | 1. plugins/feediron/init.php(76): trigger_error(test, 512) 2. classes/rssutils.php(755): hook_article_filter(Array) 3. update.php(417): update_rss_feed(129)
```
* switch back to syslog logging for example
Everything works fine.

**Comment by dugite-code** [comment]
Thanks for the Info. The Logging for FeedIron hasn't really been modified at since TT-RSS switched on PDO so I'm not surprised there is some incompatibilities

**Comment by dugite-code** [comment]
Just an Update, [Fox has recently implemented](https://discourse.tt-rss.org/t/proper-way-to-do-logging-in-a-plugin/1401/3) some changes in TT-RSS that will allow me to fix this issue.

Long and short due to calling an exception TT-RSS sanely tries to roll back any changes to the database to prevent data loss. When we do this mid process it causes issues. The new changes will allow us to call a logging exception instead.

**Comment by dugite-code** [comment]
FYI you will need TT-RSS with git commit [4f17c3f977](https://git.tt-rss.org/fox/tt-rss/commit/4f17c3f977d419aeba6c02a9a7dcc746f630fd90) or newer to take advantage of this
